### ISSUE TITLE
url is not right

### ISSUE THREAD

**Issue by xianghx** [syohex/emacs-gitignore#1]
url is     https://www.gitignore.io/api/list

ido-vertical-mode         android etc   does not work and align

Can you add package to melpa?

**Comment by syohex** [comment]
Thanks for report. I've fixed at #2.

> Can you add package to melpa?

No. [helm-gitignore](https://github.com/jupl/helm-gitignore) is already registered.

**Comment by sshaw** [comment]
>> Can you add package to melpa?

> No. helm-gitignore is already registered.

But that requires helm, amongst others. This is much more lightweight.

**Comment by syohex** [comment]
Ah, I'll rewrite some code and consider again.
